// Deterministic fixtures so the studio (and its tests) run without a live server.
// These are NOT fabricated production output — they are clearly-labelled sample
// data used only when the backend is unreachable or in unit tests.

import { BackendTimelinePayload } from "./adapter";

export function deterministicTimelinePayload(): BackendTimelinePayload {
  return {
    timeline: {
      version: "1.0",
      fps: 30,
      target_duration_seconds: 12,
      total_frames: 360,
      width: 1920,
      height: 1080,
      layers: [
        {
          id: "bg1",
          type: "video",
          track: 0,
          start_frame: 0,
          duration_frames: 360,
          z: 0,
          enabled: true,
          locked: false,
          opacity: 1,
          text: "Opening shot",
          source: null,
        },
        {
          id: "title1",
          type: "text",
          track: 1,
          start_frame: 20,
          duration_frames: 120,
          z: 3,
          enabled: true,
          locked: false,
          opacity: 1,
          text: "Sample Composition",
          source: null,
        },
        {
          id: "cap1",
          type: "caption",
          track: 1,
          start_frame: 160,
          duration_frames: 120,
          z: 3,
          enabled: true,
          locked: false,
          opacity: 1,
          text: "This is fixture data — connect a project to edit the real film.",
          source: null,
        },
        {
          id: "narr1",
          type: "narration",
          track: 2,
          start_frame: 10,
          duration_frames: 340,
          z: 1,
          enabled: true,
          locked: false,
          opacity: 1,
          source: null,
        },
        {
          id: "music1",
          type: "music",
          track: 2,
          start_frame: 0,
          duration_frames: 360,
          z: 0,
          enabled: true,
          locked: false,
          opacity: 1,
          source: null,
        },
      ],
    },
    etag: "fixture-etag",
    persisted: false,
    fps: 30,
    total_frames: 360,
    target_duration_seconds: 12,
    target_formatted: "0:12",
    word_budget: 30,
    measured_output_seconds: null,
    remotion_render_ready: false,
    remotion_reason: "Fixture mode — no live runtime probe.",
    layer_types: [
      "video",
      "image",
      "text",
      "shape",
      "caption",
      "narration",
      "music",
      "sfx",
    ],
  };
}
